### ISSUE TITLE
Update incident documentation: never make manual changes

### ISSUE THREAD

**Issue by scleary1cs** [CDCgov/trusted-intermediary#1353]
# DevEx/OpEx

Confirm whether it is/isn’t okay to ever make manual changes to files - currently assuming no. Add to incident docs to never do this.

## Tasks

- [x] Add to [incident docs](https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#1265955365f580fe824fe459d61d30c9).

## Additional Context

Add any other context or screenshots about the work here.

**Comment by jcrichlake** [comment]
Need clarity on this before it can be worked

**Comment by jherrflexion** [comment]
@JohnNKing @scleary1cs Are you able to provide more clarity on this? Is this something we need to talk to our partners about?

**Comment by JohnNKing** [comment]
@jherrflexion This pertained to a Game Day scenario where HL7 parsing failed due to a non-numeric data in a numeric (NM) observation. My take is that manual message changes in Production is something we should never allow, no matter how minor, as doing so may get us into trouble with CLIA. In this case, it would have meant changing an observation value -- which is a pretty serious no-no as it may have clinical significance.

If the sender insists we make a manual change, then we would absolutely need the receiving partner and CDC onboard with us doing so. As a starting point, I think a clear "do not do this" warning in our docs is appropriate.

**Comment by pluckyswan** [comment]
Added a callout for this in [notion](https://www.notion.so/flexion-cdc-ti/Process-92fb2c124c4146faa69429ec017902b0?pvs=4#1265955365f580fe824fe459d61d30c9)

**Comment by scleary1cs** [comment]
This is Shawn Cleary and I also approve this message.
